solive/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
import datetime

from .exts import db, login_manager
from config import SO_TIME


favorites = db.Table('favorites',
                     db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
                     db.Column('video_id', db.Integer, db.ForeignKey('videos.id')))


histories = db.Table('histories',
                     db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
                     db.Column('video_id', db.Integer, db.ForeignKey('videos.id')))


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    __table_args__ = {'mysql_charset': 'utf8mb4', 'mysql_collate': 'utf8mb4_unicode_ci'}

    id = db.Column(db.Integer, primary_key=True)
    nickname = db.Column(db.String(64))
    username = db.Column(db.String(64))
    password_hash = db.Column(db.String(128))
    avatar = db.Column(db.String(64), default='default.jpg')
    experience = db.Column(db.Integer, server_default=db.text('0'))
    last_seen = db.Column(db.DateTime())
    favorite = db.relationship('Video', secondary='favorites', lazy='dynamic')
    history = db.relationship('Video', secondary='histories', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @property
    def level(self):
        import math
        return int(math.sqrt(self.experience + 1))

    @property
    def exp_to_level_up(self):
        return self.level * 2 + 1

    @property
    def current_level_exp(self):
        return self.experience - self.level ** 2 + 1

    def add_exp(self, increment=1):
        self.experience += increment

    def first_seen_today(self):
        if self.last_seen is not None:
            return self.last_seen.date() != datetime.datetime.now().date()
        return True

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


class Video(db.Model):
    __tablename__ = 'videos'
    __table_args__ = {'mysql_charset': 'utf8mb4', 'mysql_collate': 'utf8mb4_unicode_ci'}

    id = db.Column(db.Integer, primary_key=True)
    created = db.Column(db.DateTime, nullable=False, server_default=db.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    source = db.Column(db.String(32))
    nickname = db.Column(db.String(32))
    room = db.Column(db.String(128), unique=True)
    title = db.Column(db.String(128))
    cover = db.Column(db.String(256))
    viewers_num = db.Column(db.Integer)
    cate = db.Column(db.String(32))
    parent_cate_name = db.Column(db.String(32), db.ForeignKey('categories.name'))

    @staticmethod
    def latest(obj, time_delta=SO_TIME):
        """
        如果obj为类对象，该方法将返回一个SQL clause（没有定义常规的__bool__方法，因此bool（返回值）会报错：
        "Boolean value of this clause is not defined."），而不是一个逻辑表达式;
        如果obj为实例对象，该方法返回正常的逻辑表达式.
        :param obj: class or instance.
        :param time_delta: an integer minutes count.
        :return: True if 'Video.created' is less than 'time_delta' minutes earlier from now, else False.
        """
        if isinstance(time_delta, int):
            time_delta = datetime.timedelta(minutes=time_delta)
        else:
            raise TypeError('need an int argument but given %s' % type(time_delta))
        return obj.created > datetime.datetime.now() - time_delta

    def to_json(self):
        return {
            'nickname': self.nickname,
            'title': self.title,
            'room': self.room,
            'cover': self.cover,
            'source': self.source,
            'viewers_num': self.viewers_num,
            'created': self.created,
            'cate': self.cate,
            'parent_cate_name': self.parent_cate_name,
            'is_live': self.latest(self, SO_TIME)
        }

    @staticmethod
    def aggregate(cate=None, time_delta=SO_TIME):
        if cate is None:
            subquery = db.session.query(Video.parent_cate_name, db.func.count('*').label('total_room'),
                                      db.func.sum(Video.viewers_num).label('total_num'))\
                .filter(Video.latest(Video, time_delta)).group_by(Video.parent_cate_name).subquery()  # 将query对象转化为类Table对象
            result = db.session.query(subquery).order_by(subquery.c.total_num.desc())
        else:
            result = db.session.query(db.func.count('*').label('total_room'),
                                      db.func.sum(Video.viewers_num).label('total_num'))\
                .filter(Video.latest(Video, time_delta)).group_by(Video.parent_cate_name == cate)  # FIXME
        return result


class Category(db.Model):
    __tablename__ = 'categories'
    __table_args__ = {'mysql_charset': 'utf8mb4', 'mysql_collate': 'utf8mb4_unicode_ci'}

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), unique=True)
    total_rooms = db.Column(db.Integer)
    total_viewers = db.Column(db.Integer)
    contains = db.relationship(Video, backref='parent_cate', lazy='dynamic')

solive/user/forms.py
from flask import current_app
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, FileField, PasswordField, SubmitField, ValidationError
from wtforms.validators import DataRequired, EqualTo, Length, Regexp
from werkzeug.datastructures import FileStorage

from ..models import User


class InfoForm(FlaskForm):
    avatar = FileField()
    nickname = StringField('昵称', validators=[DataRequired(),
                                             Regexp(r'[\u4e00-\u9fa5a-zA-Z_\d]+$', 0, message='昵称包含非法字符！')])
    submit_info = SubmitField('保存修改')

    def validate_avatar(self, field):
        if field.data != '' and  not isinstance(field.data, FileStorage):
            raise ValidationError('不合法的输入！')
        elif isinstance(field.data, FileStorage) and\
                not field.data.filename.endswith(current_app.config['ALLOWED_UPLOAD_TYPES']):
            raise ValidationError('不支持的上传格式！')

    def validate_nickname(self, field):
        if field.data == current_user.nickname:
            return
        if User.query.filter_by(nickname=field.data).first():
            raise ValidationError('昵称已存在！')


class PasswordForm(FlaskForm):
    old_pw = PasswordField('请输入旧密码', validators=[DataRequired()])
    new_pw = PasswordField('请输入新密码', validators=[DataRequired(), Length(8, 16)])
    new_pw2 = PasswordField('请再次输入新密码', validators=[DataRequired(), EqualTo('new_pw', message='两次输入不一致！')])
    submit_pw = SubmitField('保存修改')

    def validate_old_pw(self, field):
        if not current_user.verify_password(field.data):
            raise ValidationError('密码输入错误！')

solive/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from pyecharts.conf import PyEchartsConfig
from pyecharts.engine import ECHAERTS_TEMPLATE_FUNCTIONS

from .exts import db, login_manager
from .main import main as main_blueprint
from .auth import auth as auth_blueprint
from .auth.forms import LoginForm, RegisterForm
from .api import api as api_blueprint
from .user import user as user_blueprint


# the dictionary of flask extension instances
ext_dict = dict(
    mail = Mail(),
    bootstrap = Bootstrap()
)
globals().update(ext_dict)


# Define the factory function of flask application.
def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('../config.py')
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(api_blueprint, url_prefix='/api')
    app.register_blueprint(user_blueprint, url_prefix='/user')
    app.jinja_env.globals.update(ECHAERTS_TEMPLATE_FUNCTIONS)
    app.jinja_env.pyecharts_config = PyEchartsConfig(jshost='https://cdn.bootcss.com/echarts/3.7.2')

    db.init_app(app)
    login_manager.init_app(app)

    for key in ext_dict:
        ext_dict[key].init_app(app)

    def add_template_globals():
        return app.config['GLOBAL_TEMPLATE_ARGS']
    app.context_processor(add_template_globals)

    return app


from . import models

solive/api/__init__.py
from flask import Blueprint


api = Blueprint('api', __name__)


from . import videos

solive/main/__init__.py
from flask import Blueprint
from jinja2.runtime import Undefined


main = Blueprint('main', __name__)


def f(s):
    if isinstance(s, Undefined):
        return ''
    return s + '_'

main.add_app_template_filter(f)


from . import views

solive/main/views.py
from flask import render_template, url_for, flash, redirect, request, abort, jsonify
from flask_login import login_required, current_user
from pyecharts import Bar
import random
import json

from . import main
from config import SO_TIME, HOT_HOSTS, URL_CATE_MAPPINGS, CATE_URL_MAPPINGS, SO_LABELS
from ..exts import db
from ..models import Video


@main.route('/')
def index():
    # 轮播数据
    carousel = Video.query.filter(Video.latest(Video, SO_TIME)).order_by(Video.viewers_num.desc())[:5]

    # 各个直播平台直播间个数
    with open('live_crawler/live.json') as f:
        lives_num_list = sorted(json.load(f), key=lambda x: x['lives_num'], reverse=True)

    # so主播数据
    host_sample = random.sample(HOT_HOSTS, 12)
    hosts = []
    for room in host_sample:
        host = Video.query.filter(Video.room == room).first()
        if host is not None:
            if host.latest(host, SO_TIME):
                hosts.append((host, True))
            else:
                hosts.append((host, False))

    # so游戏、so娱乐数据
    render_so = {}
    render_so['game'] = Video.query.filter(Video.latest(Video, SO_TIME)) \
                            .filter(Video.cate.in_(SO_LABELS['game'])).order_by(Video.viewers_num.desc())[:8]
    render_so['entertainment'] = Video.query.filter(Video.latest(Video, SO_TIME)) \
                            .filter(Video.cate.in_(SO_LABELS['entertainment'])).order_by(Video.viewers_num.desc())[:8]
    return render_template('index.html', carousel=carousel, lives_num_list=lives_num_list, hosts=hosts,
                           render_so=render_so)


@main.route('/chart')
def chart():
    data = {
        '张三': 123.3,
        '李四': 66.8,
        '王五': 86.4,
        '杨六': 77.9,
        'ji': 46.3,
        'pp': 110.4
    }
    bar = Bar()
    v1, v2 = bar.cast(data)
    bar.add('weight', v1, v2)
    return render_template('simple_chart.html', chart=bar)


@main.route('/all')
@main.route('/all/<int:page>')
def all(page=1):
    pagination = Video.query.filter(Video.latest(Video, SO_TIME)).order_by(Video.viewers_num.desc())\
        .paginate(page, 40, False)
    return render_template('all.html', title='全部直播', pagination=pagination)


@main.route('/cate')
def cate():
    # aggregation = {}
    # for v in mappings.values():
    #     res = Video.aggregate(v, SO_TIME)
    #     aggregation[v] = [res.total_room, res.total_num]
    aggregation = Video.aggregate(time_delta=SO_TIME)
    # TODO: 按照cate_url_mappings来排序：遍历aggregation，mappings[name] = item.
    return render_template('cate.html', title='全部分类', mappings=CATE_URL_MAPPINGS, aggregation=aggregation)


@main.route('/cate/<string:name>')
@main.route('/cate/<string:name>/<int:page>')
def show_cate(name, page=1):
    if name not in URL_CATE_MAPPINGS:
        flash('您访问的页面不存在！')
        return redirect(request.referrer or url_for('.cate'))
    videos = Video.query.filter_by(parent_cate_name=URL_CATE_MAPPINGS[name]).filter(Video.latest(Video, SO_TIME))\
        .order_by(Video.viewers_num.desc())
    pagination = videos.paginate(page, 40, False)
    return render_template('all.html', title=URL_CATE_MAPPINGS[name], pagination=pagination)


@main.route('/search')
def search():
    keyword = request.args.get('keyword')
    if keyword is not None:
        videos = Video.query.filter(db.or_(Video.title.like('%{}%'.format(keyword)),
                                           Video.nickname.like('%{}%'.format(keyword))))\
            .order_by(Video.viewers_num.desc())
        if videos is not None:
            page = int(request.args.get('page') or 1)
            pagination = videos.paginate(page, 40, False)
            return render_template('search.html', title=keyword, pagination=pagination)
    return abort(404)   # TODO


@main.route('/favorite', methods=['POST'])
def favorite():
    if current_user.is_authenticated:
        data = request.form
        video = current_user.favorite.filter(Video.room == data['video']).first()
        if data['operation'] == '添加收藏':
            if video is None:
                video = Video.query.filter(Video.room == data['video']).first()
                current_user.favorite.append(video)
                operation = '取消收藏'
                return jsonify({'code': '200', 'operation': operation})
            error_message = '您已收藏这个房间，请勿重复添加！'
        elif data['operation'] == '取消收藏':
            if video is not None:
                current_user.favorite.remove(video)
                operation = '添加收藏'
                return jsonify({'code': '200', 'operation': operation})
            error_message = '您尚未收藏此房间，取消收藏失败！'
        else:
            error_message = '未知的操作！'
        return jsonify({'code': '400', 'message': error_message})
    error_message = '请登录！'
    return jsonify({'code': '401', 'message': error_message})


@main.route('/history', methods=['POST'])
def history():
    if current_user.is_authenticated:
        data = request.form
        video = Video.query.filter(Video.room == data['video']).first()
        if video is not None:
            if video not in current_user.history:
                current_user.history.append(video)
    return jsonify({})

solive/user/__init__.py
from flask import Blueprint


user = Blueprint('user', __name__)


from . import views, forms

solive/user/views.py
from flask import abort, render_template, request, jsonify
from flask_login import current_user
from werkzeug.utils import secure_filename
import datetime

from . import user
from .forms import InfoForm, PasswordForm
from ..exts import db


@user.before_request
def before_user_request():
    if not current_user.is_authenticated:
        abort(401)


@user.before_app_request
def add_experience():
    if current_user.is_authenticated:
        if current_user.first_seen_today():
            current_user.add_exp()
        current_user.last_seen = datetime.datetime.now()


@user.route('/settings', methods=['GET', 'POST'])
def settings():
    info_form = InfoForm(meta={'csrf': False})
    password_form = PasswordForm(meta={'csrf': False})
    print(info_form.data)
    if not info_form.is_submitted():
        info_form.nickname.data = current_user.nickname
    elif info_form.validate_on_submit():
        file = request.files.get('avatar', None)
        if file:
            filename = '%s.%s' % (current_user.username, file.filename.rsplit('.', 1)[-1])
            file.save('solive/static/img/avatar/%s' % filename)
            current_user.avatar = filename
        current_user.nickname = info_form.nickname.data
        db.session.add(current_user)
        db.session.commit()
    return render_template('user/settings.html', info_form=info_form, password_form=password_form)


@user.route('/password', methods=['POST'])
def password():
    form = PasswordForm(meta={'csrf': False})
    if form.validate_on_submit():
        current_user.password = form.new_pw.data
        db.session.add(current_user)
        db.session.commit()
        return jsonify({'code': 200, 'message': 'success'})
    else:
        return jsonify({'code': 400, 'message': 'error', 'data': form.errors})


@user.route('/history')
def history():
    if current_user.is_authenticated:
        pagination = current_user.history.paginate(1, 40, False)
        return render_template('user/history.html', title='观看历史', pagination=pagination)
        # TODO


@user.route('/favorite')
def favorite():
    if current_user.is_authenticated:
        pagination = current_user.favorite.paginate(1, 40, False)
        return render_template('user/favorite.html', title='我的收藏', pagination=pagination)

solive/templates/all.html
{% extends "subbase.html" %}
{% block container %}
<div class="video-container">
    {%- with videos=pagination.items %}
    {%- from "macros.html" import render_video with context %}
    {%- for video in videos -%}
        {{ render_video(video) }}
    {%- endfor -%}
    {%- endwith %}
</div>
{%- from "pagination.html" import render_pagination %}
    {{ render_pagination(pagination) }}
{% endblock %}

solive/templates/base.html
{% extends "bootbase.html" %}
{% block title %}{{title|f}}solive-搜直播{% endblock %}
{% block styles %}
    {{ super() }}
    <link href="/static/css/solive.css" rel="stylesheet">
{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Solive</a>
        </div>
        <div id="collapse-top" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">首页</a></li>
                <li><a href="{{ url_for('main.all') }}">全部</a></li>
                <li><a href="{{ url_for('main.cate') }}">分类</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="navbar-form">
                    <form action="{{ url_for('main.search') }}" method="get" class="input-group" id="keyword-form">
                        <input type="text" class="form-control" id="keyword" name="keyword" placeholder="搜索">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default" id="search">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </div>
                    </form>
                </li>
                <li><a href="javascript:" onclick="event.preventDefault();" data-toggle="modal" data-target="#register-modal">注册</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                {% else %}
                <li><a href="javascript:" data-toggle="modal" data-target="#login-modal">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script src="/static/js/solive.js"></script>
{% endblock %}
{% block modal %}
{% import "modal.html" as m with context %}
    {{ m.render_modal() }}
    {{ m.render_modal(modal_type='register-modal') }}
{% endblock %}

solive/templates/bootbase.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}
    {% block modal -%}
    {%- endblock %}
    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

solive/templates/cate.html
{% extends "subbase.html" %}
{% block container %}
<div class="video-container">
    {%- for cate in aggregation %}
        <div class="cate-box">
            <a href="{{ url_for('main.show_cate', name=mappings[cate.parent_cate_name]) }}" class="thumbnail">
                <img src="static/img/cate/{{ cate.parent_cate_name }}.jpg" alt="{{ cate.parent_cate_name }}">
                <div class="cate-info">
                    <span class="cate-name" title="{{ cate.parent_cate_name }}">{{ cate.parent_cate_name }}</span>
                    <span class="cate-rooms" title="{{ cate.total_room }}">当前直播间个数：{{ cate.total_room }}</span>
                    <span class="cate-viewers" title="{{ cate.total_num }}">当前观看人数：{{ cate.total_num }}</span>
                </div>
            </a>
        </div>
    {% endfor -%}
</div>
{% endblock %}

solive/templates/index.html
{% extends 'base.html' %}
{% from "macros.html" import render_video with context %}
{% block content %}
<div class="solive-container" style="padding-top: 70px;">
    <div class="row">
        <div class="col-sm-7 col-xs-7">
            <div id="room-carousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {%- for i in range(5) %}
                    <li data-target="#room-carousel" data-slide-to="{{ i }}"
                            {%- if loop.first %} class="active"{% endif -%}>
                    </li>
                    {% endfor -%}
                </ol>
                <div class="carousel-inner">
                    {%- for item in carousel %}
                    <a href="{{ item.room }}"  target="_blank" class="item{% if loop.first %} active{% endif %}">
                        <img src="{{ item.cover }}" referrerPolicy="no-referrer">
                        <div class="carousel-caption">
                            <strong>{{ item.nickname }}：</strong>{{ item.title }}
                        </div>
                    </a>
                    {% endfor -%}
                </div>
                <a class="left carousel-control" href="#room-carousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#room-carousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
        <div class="col-sm-5 col-xs-5">
            <div class="source">
                <p class="source-title">直播平台</p>
                <ul class="source-list">
                    {%- for item in lives_num_list %}
                    <li><a href="{{ config['SOURCE_INDEX_MAPPINGS'][item.platform] }}" target="_blank">
                        <img src="/static/img/logo/{{ item.platform }}.jpg">
                        {{ config['URL_SOURCE_MAPPINGS'][item.platform] }}直播
                        <span>{{ item.lives_num }}个直播</span></a></li>
                    {% endfor -%}
                </ul>
            </div>
        </div>
    </div>
    <div class="so-panel clearfix">
        <div class="so-panel-header">
            <span class="so-panel-title">So主播</span>
            <div id="so-control" class="so-control">
                <div class="so-group">
                    <label for="select-source">平台</label>
                    <select id="select-source" name="source" class="so-select">
                        <option>全部</option>
                        <option>斗鱼</option>
                        <option>熊猫</option>
                        <option>虎牙</option>
                        <option>全民</option>
                        <option>龙珠</option>
                        <option>战旗</option>
                        <option>bilibili</option>
                    </select>
                </div>
                <div class="so-group">
                    <label for="select-cate">分类</label>
                    <select id="select-cate" name="cate" class="so-select">
                        <option>全部</option>
                        <option>英雄联盟</option>
                        <option>绝地求生</option>
                        <option>DNF</option>
                        <option>王者荣耀</option>
                        <option>穿越火线</option>
                        <option>DOTA2</option>
                        <option>炉石传说</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="so-panel-body">
            <div class="so-list">
                {%- for item in hosts %}
                <a href="{{ item[0].room }}" target="_blank"{% if item[1] %} class="live"{% endif %}>
                    <div class="host-name">
                        <span title="{{ item[0].nickname }}">{{ item[0].nickname }}</span>
                        {% if item[1] %}<i class="badge">live</i>{% endif %}
                    </div>
                    <span class="host-cate" title="{{ item[0].cate }}">{{ item[0].cate }}</span>
                    <span class="host-source" title="{{ item[0].source }}">{{ item[0].source }}</span>
                </a>
                {% endfor -%}
            </div>
        </div>
    </div>
    <div class="so-panel clearfix">
        <div class="so-panel-header">
            <span class="so-panel-title">So游戏</span>
            {%- for label in config['SO_LABELS']['game'] %}
            <label class="cate-label">{{ label }}</label>
            {% endfor -%}
        </div>
        <div class="so-panel-body">
            {%- for video in render_so['game'] %}
                {{ render_video(video) }}
            {% endfor -%}
        </div>
    </div>
    <div class="so-panel clearfix">
        <div class="so-panel-header">
            <span class="so-panel-title">So娱乐</span>
            {%- for label in config['SO_LABELS']['entertainment'] %}
            <label class="cate-label">{{ label }}</label>
            {% endfor -%}
        </div>
        <div class="so-panel-body">
            {%- for video in render_so['entertainment'] %}
                {{ render_video(video) }}
            {% endfor -%}
        </div>
    </div>
</div>
{% endblock %}

solive/templates/subbase.html
{% extends "base.html" %}
{% block content %}
<input id="toggleSidebarCheck" type="checkbox" style="display: none;">
<div class="sidebar">
    {% if current_user.is_authenticated %}
    <div class="user-info">
        <div class="square">
            <img src="/static/img/avatar/{{ current_user.avatar }}" class="avatar">
        </div>
        <div class="user-name">
            <a href="#">{{ current_user.nickname }}</a>
        </div>
        <div class="level">
            <div>lv{{ current_user.level }}:</div>
            <div class="progress">
                <span class="progress-bar progress-bar-danger"
                      style="width: {{ current_user.current_level_exp / current_user.exp_to_level_up * 100 }}%;"></span>
            </div>
            <div>{{ current_user.current_level_exp }} / {{ current_user.exp_to_level_up }}</div>
        </div>
        <div class="user-options">
            <a href="{{ url_for('user.history') }}"><span class="glyphicon glyphicon-time"></span>观看历史</a>
            <a href="{{ url_for('user.favorite') }}"><span class="glyphicon glyphicon-star"></span>我的收藏</a>
            <a href="{{ url_for('user.settings') }}"><span class="glyphicon glyphicon-edit"></span>资料设置</a>
            <a href="{{ url_for('auth.logout') }}"><span class="glyphicon glyphicon-off"></span>退出登录</a>
        </div>
    </div>
    {% endif %}
    <ul class="nav nav-pills nav-stacked">
        <li><a href="{{ url_for('main.all') }}"><span class="glyphicon glyphicon-expand" style="padding-right: 8%;"></span>全部直播</a></li>
        <li><a href="{{ url_for('main.cate') }}"><span class="glyphicon glyphicon-th-large" style="padding-right: 8%;"></span>全部分类</a></li>
    </ul>
    <div class="sidebar-recommend">
        <div class="sidebar-recommend-title">
            <span>推荐分类</span>
        </div>
        <ul class="sidebar-recommend-cate">
            {%- for item in config.GLOBAL_TEMPLATE_ARGS['recommend'] %}
            <li><a href="/cate/{{ cate_url_mappings[item] }}">{{ item }}<span class="badge">HOT</span></a></li>
            {% endfor -%}
        </ul>
    </div>
    <div class="sidebar-categories">
        {%- for category, lst in categories.items() %}
        <div class="sidebar-category">
            <div class="sidebar-category-name">
                <a href="###">{{ category }}</a>
                <div class="triangle-btn" data-toggle="collapse" data-target="#cate-{{ loop.index }}">
                    <span class="caret"></span>
                </div>
            </div>
            <div class="collapse sidebar-subcate" id="cate-{{ loop.index }}">
                {%- for item in lst %}
                <a href="/cate/{{ cate_url_mappings[item] }}">{{ item }}</a>
                {% endfor -%}
            </div>
        </div>
        {% endfor -%}
    </div>
</div>
<div class="sidebar-control">
    <label for="toggleSidebarCheck" class="rotated-arrow"></label>
    <label for="toggleSidebarCheck" class="click-zone"></label>
</div>
<div class="right-container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block container %}
    {% endblock %}
</div>
{% endblock %}